/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudiogramExplainedRouteImport } from './routes/audiogram-explained'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BayesianHearingTestRouteImport } from './routes/bayesian-hearing-test'
import { Route as DataRouteImport } from './routes/data'
import { Route as HeadphoneHearingTestAccuracyRouteImport } from './routes/headphone-hearing-test-accuracy'
import { Route as HearingLossPreventionRouteImport } from './routes/hearing-loss-prevention'
import { Route as HearingThresholdsRouteImport } from './routes/hearing-thresholds'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HowOnlineHearingTestsWorkRouteImport } from './routes/how-online-hearing-tests-work'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as ScienceRouteImport } from './routes/science'
import { Route as TestRouteImport } from './routes/test'
import { Route as TrainRouteImport } from './routes/train'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as CoachThreadIdRouteImport } from './routes/coach.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiogramExplainedRoute = AudiogramExplainedRouteImport.update({
  id: '/audiogram-explained',
  path: '/audiogram-explained',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BayesianHearingTestRoute = BayesianHearingTestRouteImport.update({
  id: '/bayesian-hearing-test',
  path: '/bayesian-hearing-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadphoneHearingTestAccuracyRoute =
  HeadphoneHearingTestAccuracyRouteImport.update({
    id: '/headphone-hearing-test-accuracy',
    path: '/headphone-hearing-test-accuracy',
    getParentRoute: () => rootRouteImport,
  } as any)
const HearingLossPreventionRoute = HearingLossPreventionRouteImport.update({
  id: '/hearing-loss-prevention',
  path: '/hearing-loss-prevention',
  getParentRoute: () => rootRouteImport,
} as any)
const HearingThresholdsRoute = HearingThresholdsRouteImport.update({
  id: '/hearing-thresholds',
  path: '/hearing-thresholds',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HowOnlineHearingTestsWorkRoute =
  HowOnlineHearingTestsWorkRouteImport.update({
    id: '/how-online-hearing-tests-work',
    path: '/how-online-hearing-tests-work',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceRoute = ScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachThreadIdRoute = CoachThreadIdRouteImport.update({
  id: '/coach/$threadId',
  path: '/coach/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audiogram-explained': typeof AudiogramExplainedRoute
  '/auth': typeof AuthRoute
  '/bayesian-hearing-test': typeof BayesianHearingTestRoute
  '/data': typeof DataRoute
  '/headphone-hearing-test-accuracy': typeof HeadphoneHearingTestAccuracyRoute
  '/hearing-loss-prevention': typeof HearingLossPreventionRoute
  '/hearing-thresholds': typeof HearingThresholdsRoute
  '/history': typeof HistoryRoute
  '/how-online-hearing-tests-work': typeof HowOnlineHearingTestsWorkRoute
  '/report': typeof ReportRoute
  '/risks': typeof RisksRoute
  '/science': typeof ScienceRoute
  '/test': typeof TestRoute
  '/train': typeof TrainRoute
  '/api/chat': typeof ApiChatRoute
  '/coach/$threadId': typeof CoachThreadIdRoute
  '/coach/': typeof CoachIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiogram-explained': typeof AudiogramExplainedRoute
  '/auth': typeof AuthRoute
  '/bayesian-hearing-test': typeof BayesianHearingTestRoute
  '/data': typeof DataRoute
  '/headphone-hearing-test-accuracy': typeof HeadphoneHearingTestAccuracyRoute
  '/hearing-loss-prevention': typeof HearingLossPreventionRoute
  '/hearing-thresholds': typeof HearingThresholdsRoute
  '/history': typeof HistoryRoute
  '/how-online-hearing-tests-work': typeof HowOnlineHearingTestsWorkRoute
  '/report': typeof ReportRoute
  '/risks': typeof RisksRoute
  '/science': typeof ScienceRoute
  '/test': typeof TestRoute
  '/train': typeof TrainRoute
  '/api/chat': typeof ApiChatRoute
  '/coach/$threadId': typeof CoachThreadIdRoute
  '/coach': typeof CoachIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audiogram-explained': typeof AudiogramExplainedRoute
  '/auth': typeof AuthRoute
  '/bayesian-hearing-test': typeof BayesianHearingTestRoute
  '/data': typeof DataRoute
  '/headphone-hearing-test-accuracy': typeof HeadphoneHearingTestAccuracyRoute
  '/hearing-loss-prevention': typeof HearingLossPreventionRoute
  '/hearing-thresholds': typeof HearingThresholdsRoute
  '/history': typeof HistoryRoute
  '/how-online-hearing-tests-work': typeof HowOnlineHearingTestsWorkRoute
  '/report': typeof ReportRoute
  '/risks': typeof RisksRoute
  '/science': typeof ScienceRoute
  '/test': typeof TestRoute
  '/train': typeof TrainRoute
  '/api/chat': typeof ApiChatRoute
  '/coach/$threadId': typeof CoachThreadIdRoute
  '/coach/': typeof CoachIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audiogram-explained'
    | '/auth'
    | '/bayesian-hearing-test'
    | '/data'
    | '/headphone-hearing-test-accuracy'
    | '/hearing-loss-prevention'
    | '/hearing-thresholds'
    | '/history'
    | '/how-online-hearing-tests-work'
    | '/report'
    | '/risks'
    | '/science'
    | '/test'
    | '/train'
    | '/api/chat'
    | '/coach/$threadId'
    | '/coach/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audiogram-explained'
    | '/auth'
    | '/bayesian-hearing-test'
    | '/data'
    | '/headphone-hearing-test-accuracy'
    | '/hearing-loss-prevention'
    | '/hearing-thresholds'
    | '/history'
    | '/how-online-hearing-tests-work'
    | '/report'
    | '/risks'
    | '/science'
    | '/test'
    | '/train'
    | '/api/chat'
    | '/coach/$threadId'
    | '/coach'
  id:
    | '__root__'
    | '/'
    | '/audiogram-explained'
    | '/auth'
    | '/bayesian-hearing-test'
    | '/data'
    | '/headphone-hearing-test-accuracy'
    | '/hearing-loss-prevention'
    | '/hearing-thresholds'
    | '/history'
    | '/how-online-hearing-tests-work'
    | '/report'
    | '/risks'
    | '/science'
    | '/test'
    | '/train'
    | '/api/chat'
    | '/coach/$threadId'
    | '/coach/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudiogramExplainedRoute: typeof AudiogramExplainedRoute
  AuthRoute: typeof AuthRoute
  BayesianHearingTestRoute: typeof BayesianHearingTestRoute
  DataRoute: typeof DataRoute
  HeadphoneHearingTestAccuracyRoute: typeof HeadphoneHearingTestAccuracyRoute
  HearingLossPreventionRoute: typeof HearingLossPreventionRoute
  HearingThresholdsRoute: typeof HearingThresholdsRoute
  HistoryRoute: typeof HistoryRoute
  HowOnlineHearingTestsWorkRoute: typeof HowOnlineHearingTestsWorkRoute
  ReportRoute: typeof ReportRoute
  RisksRoute: typeof RisksRoute
  ScienceRoute: typeof ScienceRoute
  TestRoute: typeof TestRoute
  TrainRoute: typeof TrainRoute
  ApiChatRoute: typeof ApiChatRoute
  CoachThreadIdRoute: typeof CoachThreadIdRoute
  CoachIndexRoute: typeof CoachIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiogram-explained': {
      id: '/audiogram-explained'
      path: '/audiogram-explained'
      fullPath: '/audiogram-explained'
      preLoaderRoute: typeof AudiogramExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bayesian-hearing-test': {
      id: '/bayesian-hearing-test'
      path: '/bayesian-hearing-test'
      fullPath: '/bayesian-hearing-test'
      preLoaderRoute: typeof BayesianHearingTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headphone-hearing-test-accuracy': {
      id: '/headphone-hearing-test-accuracy'
      path: '/headphone-hearing-test-accuracy'
      fullPath: '/headphone-hearing-test-accuracy'
      preLoaderRoute: typeof HeadphoneHearingTestAccuracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hearing-loss-prevention': {
      id: '/hearing-loss-prevention'
      path: '/hearing-loss-prevention'
      fullPath: '/hearing-loss-prevention'
      preLoaderRoute: typeof HearingLossPreventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hearing-thresholds': {
      id: '/hearing-thresholds'
      path: '/hearing-thresholds'
      fullPath: '/hearing-thresholds'
      preLoaderRoute: typeof HearingThresholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-online-hearing-tests-work': {
      id: '/how-online-hearing-tests-work'
      path: '/how-online-hearing-tests-work'
      fullPath: '/how-online-hearing-tests-work'
      preLoaderRoute: typeof HowOnlineHearingTestsWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science': {
      id: '/science'
      path: '/science'
      fullPath: '/science'
      preLoaderRoute: typeof ScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/$threadId': {
      id: '/coach/$threadId'
      path: '/coach/$threadId'
      fullPath: '/coach/$threadId'
      preLoaderRoute: typeof CoachThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudiogramExplainedRoute: AudiogramExplainedRoute,
  AuthRoute: AuthRoute,
  BayesianHearingTestRoute: BayesianHearingTestRoute,
  DataRoute: DataRoute,
  HeadphoneHearingTestAccuracyRoute: HeadphoneHearingTestAccuracyRoute,
  HearingLossPreventionRoute: HearingLossPreventionRoute,
  HearingThresholdsRoute: HearingThresholdsRoute,
  HistoryRoute: HistoryRoute,
  HowOnlineHearingTestsWorkRoute: HowOnlineHearingTestsWorkRoute,
  ReportRoute: ReportRoute,
  RisksRoute: RisksRoute,
  ScienceRoute: ScienceRoute,
  TestRoute: TestRoute,
  TrainRoute: TrainRoute,
  ApiChatRoute: ApiChatRoute,
  CoachThreadIdRoute: CoachThreadIdRoute,
  CoachIndexRoute: CoachIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
